### ISSUE TITLE
Add `port`configuration option and parameter

### ISSUE THREAD

**Issue by mwittig** [pushchris/hue-module#3]
Nice to have. It would be great to be able to provide a port other than the default port (80) for testing purposes. I am currently testing with the HueEmulator. As port 80 is already in use I am using the emulator on port 8080. It is supported by other packages such as `node-hue-api`. However, I would like to use `hue-module` as it is more light-weight.

**Comment by pushchris** [comment]
@mwittig I added a port parameter so that you can set this to whatever you would please. Do let me know if you find any bugs when setting the port to something different.

**Comment by mwittig** [comment]
@pushchris Oh, that's great! Thank you. I'll give it a try asap
